name: emacs-tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        emacs-version:
          - 26
          - 27
          - 28
    steps:
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matix.emacs-version }}
      - name: Run tests
        run:
          make tests
